(let Tuple/new (lambda a b (tuple a b)))
(let Tuple/swap std/tuple/swap)
(let Tuple/map std/tuple/map)
(let Tuple/map/fst std/tuple/map/fst)
(let Tuple/map/snd std/tuple/map/snd)

(let Vector->Tuple (lambda fn1 fn2 xs (std/convert/vector->tuple xs fn1 fn2)))
(let Tuple/int/add std/tuple/int/add)
(let Tuple/int/sub std/tuple/int/sub)
(let Tuple/int/mul std/tuple/int/mul)
(let Tuple/int/div std/tuple/int/div)

(let Tuple/bool/eq? (lambda { a b } (=? a b)))
(let Tuple/int/eq? (lambda { a b } (= a b)))
(let Tuple/char/eq? (lambda { a b } (=# a b)))
(let Tuple/float/eq? (lambda { a b } (=. a b)))

(let Tuple/bool/not-eq? (lambda { a b } (not (=? a b))))
(let Tuple/int/not-eq? (lambda { a b } (not (= a b))))
(let Tuple/char/not-eq? (lambda { a b } (not (=# a b))))
(let Tuple/float/not-eq? (lambda { a b } (not (=. a b))))

(let Int->Alphabet std/convert/int->char/alphabet)

(let Integer->Chars std/convert/integer->string)
(let Integer->String std/convert/integer->string)
(let Float->Chars std/convert/float->string)
(let Float->String std/convert/float->string)

(let String->Vector (lambda ch xs (std/convert/string->vector xs ch)))
(let Vector->String (lambda ch xs (std/convert/vector->string xs ch)))
(let Chars->Digits std/convert/chars->digits)
(let Digits->Integer std/convert/digits->integer)
(let Chars->Integer std/convert/chars->integer)
(let String->Integer std/convert/chars->integer)
(let String->Float std/convert/chars->float)
(let Chars->Float std/convert/chars->float)
(let Integer->Bits std/convert/integer->bits)

(let Char->Digit std/convert/char->digit)
(let Digit->Char std/convert/digit->char)

(let Integer->Digits std/convert/integer->digits)
(let Digits->Chars std/convert/digits->chars)
(let Set->Vector std/convert/set->vector)
(let Vector->Set std/convert/vector->set)

(let Vector/equal? (lambda fn? xs ys (std/vector/equal? xs ys fn?)))

(let Que/new std/vector/deque/new)
(let Que/empty? std/vector/deque/empty?)
(let Que/not-empty? std/vector/queue/not-empty?)
(let Que/empty! (lambda q (do (std/vector/deque/empty! q) nil)))
(let Que/enque! (lambda xs v(do (std/vector/queue/enqueue! xs v) nil)))
(let Que/deque! (lambda queue (do (std/vector/deque/tail! queue) nil)))
(let Que/peek std/vector/deque/first)
(let Que/push! (lambda xs v (do (std/vector/deque/append! xs v) nil)))
(let Que/pop! (lambda queue (do (std/vector/deque/head! queue) nil)))
(let Que/prepend! (lambda xs v (do (std/vector/deque/prepend! xs v) nil))) 
(let Que/first std/vector/deque/first)
(let Que/last std/vector/deque/last)
(let Que/tail! (lambda queue (do (std/vector/deque/tail! queue) nil)))
(let Que/append! (lambda xs v (do (std/vector/deque/append! xs v) nil)))

(let Vector->Que std/convert/vector->deque)
(let Que->Vector std/convert/deque->vector)
(let Que/get std/vector/deque/get)
(let Que/length std/vector/deque/length)
(let Que/at (lambda i xs (if (< i 0) (std/vector/deque/get xs (+ (length xs) i)) (std/vector/deque/get xs i))))

(let BigInt/add std/int/big/add)
(let BigInt/sub std/int/big/sub)
(let BigInt/mul std/int/big/mul)
(let BigInt/lte? std/int/big/less-or-equal?)
(let BigInt/gte? std/int/big/greater-or-equal?)
(let BigInt/lt? std/int/big/less-than?)
(let BigInt/gt? std/int/big/greater-than?)
(let BigInt/equal? std/int/big/equal?)
(let BigInt/div std/int/big/div)
(let BigInt/square std/int/big/square)
(let BigInt/div/floor std/int/big/floor/div)
(let BigInt/div/ceal std/int/big/ceil/div)
(let BigInt/sum std/vector/int/big/sum)
(let BigInt/product std/vector/int/big/product)
(let BigInt/new std/int/big/new)
(let BigInt/pow std/int/big/pow)
(let BigInt/expt std/int/big/expt)
(let BigInt/range std/vector/int/big/range)

(let Vector/push! std/vector/push!)
(let Vector/pop! std/vector/pop!)
(let Vector/last std/vector/last)
(let Vector/first std/vector/first)
(let Vector/pull! std/vector/pop-and-get!)
(let Vector/get-unsafe (lambda idx xs (get xs idx)))
(let Vector/get* (lambda idx xs (if (and (>= idx 0) (< idx (length xs))) { true [(get xs idx)] } { false [] })))
(let Vector/at! (lambda idx xs (std/vector/at xs idx)))
(let Vector/at* (lambda idx xs (if (< idx (length xs)) { true [(std/vector/at xs idx)] } { false [] })))

(let Vector/set! (lambda xs i v (set! xs i v)))
(let Vector/length std/vector/length)
(let Vector/append! (lambda xs x (std/vector/append! xs x)))
(let Vector/cons! (lambda xs x (std/vector/cons! xs x)))
(let Vector/cons (lambda x xs (std/vector/cons xs x)))

(let Vector/new (lambda fn n (std/vector/2d/fill n fn)))
(let Matrix/new (lambda fn w h (std/vector/3d/fill w h fn)))
(let String/equal? std/vector/char/equal?)
(let String/lte? std/vector/char/lesser-or-equal?)
(let String/gte? std/vector/char/greater-or-equal?)
(let String/lt? std/vector/char/lesser?)
(let String/gt? std/vector/char/greater?)
(let String/quote (lambda str (cons "'" str "'")))
(let String/dquote (lambda str (cons [dq] str [dq])))
(let Char/eq? (lambda a b (=# a b)))
(let Int/eq? (lambda a b (= a b)))
(let Bool/eq? (lambda a b (=? a b)))
(let Float/eq? (lambda a b (=. a b)))

; data-last aliases mirroring Table/*
(let Table/size std/vector/flat/length)
(let Table/new (lambda (std/vector/hash/table 32)))
(let Table/new/capacity (lambda n (std/vector/hash/table n)))

(let Table/entries std/vector/hash/table/entries)
(let Table/keys std/vector/hash/table/keys)
(let Table/values std/vector/hash/table/values)

(let Table/get (lambda key table (std/vector/hash/table/get table key)))
(let Table/get* (lambda key table
  (if (std/vector/hash/table/has? table key)
      { true [ (snd (get (std/vector/hash/table/get table key) 0)) ] }
      { false [] })))
(let Table/get-unsafe (lambda key table (snd (get (std/vector/hash/table/get table key) 0))))

(let Table/has? (lambda key table (std/vector/hash/table/has? table key)))
(let Table/set! (lambda table key value (do (std/vector/hash/table/set! table key value) nil)))
(let Table/remove! (lambda table key (do (std/vector/hash/table/remove! table key) nil)))
(let Table/count std/vector/hash/table/count)

(let Table/drop! (lambda table keys (std/vector/hash/table/drop! table keys)))
(let Table/keep (lambda keys table (std/vector/hash/table/keep table keys)))
(let Table/omit (lambda keys table (std/vector/hash/table/omit table keys)))

(let Table/merge! (lambda table other (do (std/vector/hash/table/merge! table other) nil)))
(let Table/merge (lambda other table (std/vector/hash/table/merge table other)))

(let Table/resize! (lambda table n (do (std/vector/hash/table/resize! table n) nil)))
(let Table/compact! (lambda table (do (std/vector/hash/table/compact! table) nil)))

(let Vector->Table std/convert/vector->table)

; data-last aliases mirroring Set/*
(let Set/size std/vector/flat/length)
(let Set/values std/vector/flat-one)
(let Set/new (lambda (std/vector/hash/set 32)))
(let Set/new/capacity (lambda n (std/vector/hash/set n)))

(let Set/intersection std/vector/hash/set/intersection)
(let Set/difference std/vector/hash/set/difference)
(let Set/xor std/vector/hash/set/xor)
(let Set/union std/vector/hash/set/union)

(let Set/add! (lambda table item (do (std/vector/hash/set/add! table item) nil)))
(let Set/remove! (lambda table item (do (std/vector/hash/set/remove! table item) nil)))
(let Set/has? (lambda item table (std/vector/hash/set/has? table item)))
(let Set/resize! (lambda table n (do (std/vector/hash/set/resize! table n) nil)))
(let Set/compact! (lambda table (do (std/vector/hash/set/compact! table) nil)))

(let Vector->Set std/convert/vector->set/dynamic)

(let Heap/compare? (lambda i j fn? heap (std/heap/greater? heap i j fn?)))
(let Heap/peek! std/heap/peek)
(let Heap/push! (lambda heap value fn (std/heap/push! heap value fn)))
(let Heap/pop! (lambda heap fn (std/heap/pop! heap fn)))
(let Heap/replace! (lambda heap value fn (std/heap/replace! heap value fn)))
(let Heap/empty? std/vector/empty?)
(let Heap/not-empty? std/vector/not-empty?)
(let Heap/empty! std/vector/empty!)
(let Vector->Heap (lambda fn xs (std/convert/vector->heap xs fn)))

(let Matrix->String (comp (map (Vector->String sp)) (Vector->String nl)))
